/* ---------- Layouts ----------
   Coordinates are half-tile units: a tile at (x,y,z) covers x..x+2, y..y+2 on level z.
   Tiles may sit half a tile apart in either direction on the same level (staggered rows
   and columns), and upper-level tiles may straddle 2 or 4 tiles below. */
const rnd = n => Math.floor(Math.random() * n);
const shuffleArr = a => { for (let i = a.length - 1; i > 0; i--) { const j = rnd(i + 1); [a[i], a[j]] = [a[j], a[i]]; } return a; };

/* KMahjongg .layout format (v1.0 / v1.1). Each character is a quarter of a tile;
   '1' marks a tile's top-left corner, '2','4','3' fill the other corners. */
function parseKmahjongg(text) {
  const lines = text.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith("#"));
  if (!/^kmahjongg-layout-v1\.[01]$/.test(lines[0] || "")) throw new Error("First line must be kmahjongg-layout-v1.0 or v1.1");
  let h = 16;
  const rows = [];
  for (const l of lines.slice(1)) {
    let m;
    if ((m = /^h(\d+)$/.exec(l))) h = +m[1];
    else if (/^[wd]\d+$/.test(l)) continue;
    else if (/^[.1234]+$/.test(l)) rows.push(l);
  }
  if (!rows.length || rows.length % h) throw new Error(`Expected levels of ${h} rows, got ${rows.length} rows`);
  const t = [];
  rows.forEach((row, i) => {
    for (let x = 0; x < row.length; x++) if (row[x] === "1") t.push({ x, y: i % h, z: Math.floor(i / h) });
  });
  if (!t.length) throw new Error("No tiles found");
  return t;
}

/* Compact authoring format: one char per tile, '#' = tile. A row starting with '>'
   is shifted right by half a tile. Each level has its own dx/dy (half units). */
function fromRows(levels) {
  const t = [];
  levels.forEach((L, z) => {
    L.rows.forEach((r, ri) => {
      let sx = 0;
      if (r[0] === ">") { sx = 1; r = r.slice(1); }
      [...r].forEach((ch, ci) => { if (ch === "#") t.push({ x: (L.dx || 0) + sx + 2 * ci, y: (L.dy || 0) + 2 * ri, z }); });
    });
  });
  return t;
}

const overlap = (a, b) => Math.max(0, 2 - Math.abs(a.x - b.x)) * Math.max(0, 2 - Math.abs(a.y - b.y));
const support = (p, list) => list.reduce((s, q) => s + (q.z === p.z - 1 ? overlap(p, q) : 0), 0);

/* Remove tiles that aren't fully resting on the level below (repeat until stable). */
function dropUnsupported(list) {
  let t = list.slice(), changed = true;
  while (changed) {
    const keep = t.filter(p => p.z === 0 || support(p, t) === 4);
    changed = keep.length !== t.length;
    t = keep;
  }
  return t;
}

const KMJ_TURTLE = `kmahjongg-layout-v1.1
w32
h16
d5
...121212121212121212121212.....
...434343434343434343434343.....
.......1212121212121212.........
.......4343434343434343.........
.....12121212121212121212.......
.....43434343434343434343.......
...121212121212121212121212.....
.124343434343434343434343431212.
.431212121212121212121212124343.
...434343434343434343434343.....
.....12121212121212121212.......
.....43434343434343434343.......
.......1212121212121212.........
.......4343434343434343.........
...121212121212121212121212.....
...434343434343434343434343.....
................................
................................
.........121212121212...........
.........434343434343...........
.........121212121212...........
.........434343434343...........
.........121212121212...........
.........434343434343...........
.........121212121212...........
.........434343434343...........
.........121212121212...........
.........434343434343...........
.........121212121212...........
.........434343434343...........
................................
................................
................................
................................
................................
................................
...........12121212.............
...........43434343.............
...........12121212.............
...........43434343.............
...........12121212.............
...........43434343.............
...........12121212.............
...........43434343.............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
.............1212...............
.............4343...............
.............1212...............
.............4343...............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............12................
..............43................
................................
................................
................................
................................
................................
................................
................................`;

const KMJ_SPIDER = `kmahjongg-layout-v1.1
w32
h16
d4
......1212...12..12...1212......
......4343...43..43...4343......
........12....1212....12........
..12....4312..4343..1243....12..
..4312....431212121243....1243..
....431212..43434343..121243....
......43431212121212124343......
..........434343434343..........
.........12121212121212.........
.121212124343434343434312121212.
.43434343.121212121212.43434343.
..........434343434343..........
........12..12121212..12........
......1243..43434343..4312......
..121243......1212......431212..
..4343........4343........4343..
......1212...12..12...1212......
......4343...43..43...4343......
........12............12........
..12....4312........1243....12..
..4312....43..1212..43....1243..
....431212....4343....121243....
......4343..12121212..4343......
............43434343............
...........1212121212...........
.12121212..4343434343..12121212.
.43434343...12121212...43434343.
............43434343............
........12....1212....12........
......1243....4343....4312......
..121243......1212......431212..
..4343........4343........4343..
........12............12........
........43............43........
................................
..12......12........12......12..
..43......43........43......43..
......12................12......
......43......1212......43......
..............4343..............
.............121212.............
.12..12......434343......12..12.
.43..43.......1212.......43..43.
..............4343..............
..............1212..............
......12......4343......12......
..12..43................43..12..
..43........................43..
................................
................................
................................
................................
................................
................................
................................
................................
................................
...............12...............
...............43...............
................................
................................
................................
................................
................................`;

const KMJ_EXPLOSION = `kmahjongg-layout-v1.0
...12...12...121212...12...12...
.124312.43...434343...43.124312.
.431243.12..12121212..12.431243.
.124312.43..43434343..43.124312.
.431243....1212121212....431243.
...43....12434343434312....43...
.......124312......124312.......
121212.431243..12..431243.121212
434343.124312..43..124312.434343
.......431243......431243.......
...12....43121212121243....12...
.124312....4343434343....124312.
.431243.12..12121212..12.431243.
.124312.43..43434343..43.124312.
.431243.12...121212...12.431243.
...43...43...434343...43...43...
...............12...............
...12...12.....43.....12...12...
.124312.43...121212...43.124312.
.431243......434343......431243.
...43..........12..........43...
...............43...............
.........12..........12.........
.1212..124312..12..124312..1212.
.4343..431243..43..431243..4343.
.........43..........43.........
...............12...............
...12..........43..........12...
.124312......121212......124312.
.431243.12...434343...12.431243.
...43...43.....12.....43...43...
...............43...............
................................
................................
...12..........12..........12...
...43..........43..........43...
................................
................................
................................
..12.....12..........12.....12..
..43.....43..........43.....43..
................................
................................
................................
...12..........12..........12...
...43..........43..........43...
................................
................................
................................
................................
...12......................12...
...43......................43...
................................
................................
................................
................................
................................
................................
................................
................................
...12......................12...
...43......................43...
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................`;

function generatedLayout() {
  const C = 12; // board centre in half units
  const extent = list => Math.max(...list.map(p => Math.abs(p.x + 1 - C)));
  for (let tries = 0; tries < 400; tries++) {
    const L0 = [], R = 6 + rnd(3), starts = [];
    let n = 7 + rnd(5);
    for (let r = 0; r < R; r++) {
      // mostly even steps keep rows aligned; an occasional odd step staggers a row by half a tile
      if (r) n += Math.random() < .3 ? (rnd(2) ? 1 : -1) : (rnd(3) - 1) * 2;
      n = Math.max(4, Math.min(12, n));
      const start = C - n;
      starts.push(start);
      const holes = new Set();
      if (r > 0 && r < R - 1 && n >= 6 && Math.random() < .4) {
        const k = 1 + rnd(Math.floor(n / 2) - 1);
        holes.add(k); holes.add(n - 1 - k);
      }
      for (let k = 0; k < n; k++) if (!holes.has(k)) L0.push({ x: start + 2 * k, y: 2 * r, z: 0 });
    }
    if (Math.random() < .6) {                  // turtle-style wing tiles between two rows
      const r = 1 + rnd(R - 3);
      let X = Math.min(starts[r], starts[r + 1]) - 2;
      for (let i = 0, len = 1 + rnd(2); i < len; i++, X -= 2) {
        L0.push({ x: X, y: 2 * r + 1, z: 0 }, { x: 2 * C - 2 - X, y: 2 * r + 1, z: 0 });
      }
    }
    const t = L0.slice();
    let lower = L0;
    const levels = 3 + rnd(3);
    for (let z = 1; z < levels; z++) {
      const ys = lower.map(p => p.y);
      const minY = Math.min(...ys) + rnd(2), maxY = Math.max(...ys) - rnd(2);
      const limit = extent(lower) - 1 - rnd(3);  // each level pulls in from the one below
      const layer = [];
      for (let Y = minY; Y <= maxY; Y += 2) {
        const cands = [];
        for (let X = C - 1 - limit; X <= C - 1 + limit; X++) {
          const p = { x: X, y: Y, z };
          if (lower.reduce((s, q) => s + overlap(p, q), 0) === 4) cands.push(X);
        }
        cands.sort((a, b) => Math.abs(a + 1 - C) - Math.abs(b + 1 - C));
        const chosen = [], free = v => chosen.every(c => Math.abs(c - v) >= 2);
        for (const X of cands) {
          const M = 2 * C - 2 - X;
          if (!cands.includes(M)) continue;
          if (X === M) { if (free(X)) chosen.push(X); }
          else if (free(X) && free(M) && Math.abs(X - M) >= 2) chosen.push(X, M);
        }
        chosen.forEach(X => layer.push({ x: X, y: Y, z }));
      }
      if (layer.length < 2) break;
      t.push(...layer);
      lower = layer;
    }
    const levelsUsed = Math.max(...t.map(p => p.z)) + 1;
    if (t.length >= 84 && t.length <= 144 && levelsUsed >= 3) return t;
  }
  return parseKmahjongg(KMJ_TURTLE);
}

/* Random stacked board modelled on current mobile Mahjong games: a dense base
   grid (some columns dropped half a tile), then 2-3 levels whose tiles are mostly
   placed half a tile off the tiles below, so they straddle two or four of them. */
let SMALL_BOARD = false;   // phone-sized puzzle
function randomStackLayout() {
  const wrap = typeof document !== "undefined" && document.getElementById("boardWrap");
  const portrait = SMALL_BOARD || (wrap ? wrap.clientHeight > wrap.clientWidth : false);
  const [minTiles, maxTiles] = SMALL_BOARD ? [36, 64] : [96, 144];
  for (let tries = 0; tries < 300; tries++) {
    const W = SMALL_BOARD ? 4 + rnd(2) : portrait ? 6 + rnd(2) : 9 + rnd(3);
    const H = SMALL_BOARD ? 5 + rnd(2) : portrait ? 7 + rnd(3) : 5 + rnd(2);
    const sym = Math.random() < .65;
    const mirrorX = X => 2 * W - 2 - X;
    const colShift = [];
    for (let c = 0; c < W; c++) colShift[c] = sym && c >= W - 1 - c ? colShift[W - 1 - c] : (Math.random() < .22 ? 1 : 0);
    const base = [];
    const holeP = SMALL_BOARD ? .03 + Math.random() * .07 : .06 + Math.random() * .12;
    for (let c = 0; c < W; c++) for (let r = 0; r < H; r++) {
      const src = sym && c > W - 1 - c ? W - 1 - c : c;
      const key = `${src},${r}`;
      base.holes ||= {};
      if (!(key in base.holes)) base.holes[key] = Math.random() < holeP;
      if (!base.holes[key]) base.push({ x: 2 * c, y: 2 * r + colShift[c], z: 0 });
    }
    delete base.holes;
    const t = base.slice();
    let lower = base;
    const levels = SMALL_BOARD ? 3 : 3 + rnd(2);
    for (let z = 1; z < levels; z++) {
      const cands = [];
      const minY = Math.min(...base.map(p => p.y)), maxY = Math.max(...base.map(p => p.y));
      for (let X = 0; X <= 2 * W - 2; X++) for (let Y = minY; Y <= maxY; Y++) {
        const p = { x: X, y: Y, z };
        const cov = lower.reduce((s, q) => s + overlap(p, q), 0);
        if (cov < 2) continue;                 // must rest at least half on the level below
        const halfOff = lower.some(q => overlap(p, q) === 2 || overlap(p, q) === 1);
        // prefer the half-offset spots, then fully-supported ones
        cands.push({ X, Y, w: Math.random() + (halfOff ? .9 : 0) + (cov === 4 ? .3 : 0) });
      }
      cands.sort((a, b) => b.w - a.w);
      const layer = [];
      const target = Math.floor(lower.length * (.6 + Math.random() * .25));
      const clash = (X, Y) => layer.some(q => Math.abs(q.x - X) < 2 && Math.abs(q.y - Y) < 2);
      for (const { X, Y } of cands) {
        if (layer.length >= target) break;
        if (clash(X, Y)) continue;
        if (sym) {
          const M = mirrorX(X);
          if (M !== X && (Math.abs(M - X) < 2 || clash(M, Y) || !cands.some(c => c.X === M && c.Y === Y))) continue;
          layer.push({ x: X, y: Y, z });
          if (M !== X) layer.push({ x: M, y: Y, z });
        } else layer.push({ x: X, y: Y, z });
      }
      if (layer.length < 2) break;
      t.push(...layer);
      lower = layer;
    }
    if (t.length >= minTiles && t.length <= maxTiles) return t;
  }
  return generatedLayout();
}

const LAYOUTS = {
  "Random stack": randomStackLayout,
  "Turtle": () => parseKmahjongg(KMJ_TURTLE),
  "Spider": () => parseKmahjongg(KMJ_SPIDER),
  "Explosion": () => parseKmahjongg(KMJ_EXPLOSION),
  "Skull": () => dropUnsupported(fromRows([
    { rows: [
      "...#######...",
      "..#########..",
      ".###########.",
      ".##..###..##.",
      ".##..###..##.",
      ".###########.",
      "..####.####..",
      "...#######...",
      "...#.#.#.#...",
    ] },
    { dx: 1, dy: 1, rows: [
      "...######",
      "..########",
      ".#........#",
      "...........",
      ".##......##",
      "..###.###",
      "...#####",
    ] },
    { dx: 2, dy: 2, rows: ["...####", "..######"] },
    { dx: 3, dy: 3, rows: ["...###"] },
  ])),
  "Lightning Bolt": () => dropUnsupported(fromRows([
    { rows: [
      "........#####",
      ">......#####",
      ".......#####",
      ">.....#####",
      "....##########",
      ">........#####",
      "........#####",
      ">......#####",
      "......#####",
      ">....####",
      ".....###",
      ">...##",
    ] },
    { rows: [
      ".........###",
      ">.......###",
      "........###",
      ">......###",
      ".....########",
      ">.........###",
      ".........###",
      ">.......###",
      ".......###",
    ] },
    { rows: [
      "..........#",
      ">........#",
      ".........#",
      ">.......#",
      "......######",
      ">..........#",
    ] },
  ])),
  "Amp Stack": () => dropUnsupported(fromRows([
    { rows: [
      "##############",
      "##..##..##..##",
      "##..##..##..##",
      "##############",
      "##############",
      "##..##..##..##",
      "##..##..##..##",
      "##############",
    ] },
    { dx: 1, dy: 1, rows: Array(7).fill("#############") },
    { dx: 2, dy: 6, rows: ["############"] },
  ])),
  "Generated": generatedLayout,
};
const BUILTIN_KMJ = new Set(["Turtle", "Spider", "Explosion"]);

function finalizeLayout(list, allowFlip) {
  let t = list.map(p => ({ ...p }));
  if (t.length % 2) {                          // drop one tile nothing rests on
    const onTop = t.filter(p => !t.some(q => q.z === p.z + 1 && overlap(p, q)));
    const victim = onTop.sort((a, b) => b.z - a.z)[0];
    t.splice(t.indexOf(victim), 1);
  }
  if (allowFlip) {
    const maxX = Math.max(...t.map(p => p.x)), maxY = Math.max(...t.map(p => p.y));
    if (Math.random() < .5) t.forEach(p => p.x = maxX - p.x);
    if (Math.random() < .5) t.forEach(p => p.y = maxY - p.y);
  }
  const minX = Math.min(...t.map(p => p.x)), minY = Math.min(...t.map(p => p.y));
  t.forEach(p => { p.x -= minX; p.y -= minY; });
  return t;
}

/* Neighbour lists. A tile is covered by any tile one level up that overlaps it at all,
   and blocked on a side by any same-level tile directly beside it, including ones
   staggered half a tile up or down. */
function buildGeom(list) {
  const g = list.map((p, i) => ({ ...p, id: i, above: [], left: [], right: [] }));
  for (const a of g) for (const b of g) {
    if (a === b) continue;
    if (b.z === a.z + 1 && overlap(a, b)) a.above.push(b.id);
    if (b.z === a.z && Math.abs(b.y - a.y) < 2) {
      if (b.x === a.x - 2) a.left.push(b.id);
      if (b.x === a.x + 2) a.right.push(b.id);
    }
  }
  return g;
}
let SIDE_BLOCKING = true;   // classic rule; off = only tiles on top block
const freeWith = (t, alive) =>
  !t.above.some(i => alive.has(i)) &&
  (!SIDE_BLOCKING || !t.left.some(i => alive.has(i)) || !t.right.some(i => alive.has(i)));

function solvableAssign(geom, ids, facePairs) {
  for (let attempt = 0; attempt < 500; attempt++) {
    const alive = new Set(ids), pairs = shuffleArr(facePairs.slice()), asg = new Map();
    let idx = 0, ok = true;
    while (alive.size) {
      const free = [...alive].filter(i => freeWith(geom[i], alive));
      if (free.length < 2) { ok = false; break; }
      shuffleArr(free);
      asg.set(free[0], pairs[idx]); asg.set(free[1], pairs[idx]); idx++;
      alive.delete(free[0]); alive.delete(free[1]);
    }
    if (ok) return asg;
  }
  return null;
}

/* Deal faces by simulating a winning game with a tray of TRAY_SIZE slots
   (a full tray loses, so at most TRAY_SIZE-1 unmatched tiles may be held).
   pOpen = how often the simulated player takes a new album instead of completing
   one already in the tray. When a pair is completed, the generator prefers a
   partner that was NOT reachable when the first copy was taken, so the first copy
   has to sit in the tray. Returns Map(id -> face) or null. */
const TRAY_SIZE = 4;
function assignWithTray(geom, ids, pairFaces, initialOpen, pOpen, attempts = 400) {
  const cap = TRAY_SIZE - 1;
  if (initialOpen.length > cap) return null;
  for (let attempt = 0; attempt < attempts; attempt++) {
    const alive = new Set(ids), asg = new Map();
    const open = initialOpen.map(face => ({ face, reachable: new Set() }));
    let idx = 0, ok = true;
    while (alive.size) {
      const free = [...alive].filter(i => freeWith(geom[i], alive));
      if (!free.length) { ok = false; break; }
      const c = free[rnd(free.length)];
      const remaining = alive.size;
      const canOpen = idx < pairFaces.length && open.length < cap && remaining >= open.length + 2;
      const mustOpen = open.length === 0;
      if (mustOpen && !canOpen) { ok = false; break; }
      if (mustOpen || (canOpen && Math.random() < pOpen)) {
        open.push({ face: pairFaces[idx++], reachable: new Set(free) });
        asg.set(c, open[open.length - 1].face);
      } else {
        const hidden = open.filter(o => !o.reachable.has(c));
        const pool = hidden.length && Math.random() < .85 ? hidden : open;
        const pick = pool[rnd(pool.length)];
        asg.set(c, pick.face);
        open.splice(open.indexOf(pick), 1);
      }
      alive.delete(c);
    }
    if (ok && !open.length && idx === pairFaces.length) return asg;
  }
  return null;
}
